# Generated by Django 4.2.29 on 2026-05-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shipping_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='shipping_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
