# Generated by Django 4.2.30 on 2026-06-12 06:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InteractionEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("idempotency_key", models.UUIDField(blank=True, null=True, unique=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("anonymous_id", models.UUIDField(blank=True, null=True)),
                ("session_id", models.UUIDField()),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("product_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=50)),
                ("weight", models.FloatField()),
                ("source", models.CharField(default="WEB", max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("aggregate_id", models.UUIDField()),
                ("aggregate_type", models.CharField(max_length=100)),
                ("event_type", models.CharField(max_length=100)),
                ("message_id", models.UUIDField(unique=True)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.IntegerField()),
                ("customer_id", models.IntegerField()),
                ("rating", models.IntegerField()),
                ("comment_text", models.TextField(blank=True, null=True)),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("verified_purchase", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_hidden", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("customer_id", models.IntegerField()),
                ("order_id", models.IntegerField(blank=True, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Mở"),
                            ("IN_PROGRESS", "Đang xử lý"),
                            ("RESOLVED", "Đã giải quyết"),
                            ("CLOSED", "Đã đóng"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "wishlists",
                "unique_together": {("customer_id", "product_id")},
            },
        ),
        migrations.CreateModel(
            name="TicketReply",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sender_id", models.IntegerField()),
                ("is_staff", models.BooleanField(default=False)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="interaction.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_replies",
                "ordering": ["created_at"],
            },
        ),
    ]
