"""Create social tables when 0001_initial was applied before Review/Wishlist existed."""

from django.db import migrations


CREATE_MISSING_TABLES = """
CREATE TABLE IF NOT EXISTS reviews (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    customer_id integer NOT NULL,
    rating integer NOT NULL,
    comment_text text NULL,
    image_urls varchar(1000)[] NULL,
    verified_purchase boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    is_hidden boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS wishlists (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    product_id integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    UNIQUE (customer_id, product_id)
);

CREATE TABLE IF NOT EXISTS tickets (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    customer_id integer NOT NULL,
    order_id integer NULL,
    subject varchar(255) NOT NULL,
    content text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'OPEN'
);

CREATE TABLE IF NOT EXISTS ticket_replies (
    id uuid NOT NULL PRIMARY KEY,
    sender_id integer NOT NULL,
    is_staff boolean NOT NULL DEFAULT false,
    message text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    ticket_id uuid NOT NULL REFERENCES tickets(id) DEFERRABLE INITIALLY DEFERRED
);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("interaction", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(CREATE_MISSING_TABLES, migrations.RunSQL.noop),
    ]
