from django.db import migrations, models
import django.db.models.deletion


CREATE_MISSING_TABLES = """
CREATE TABLE IF NOT EXISTS brands (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    description text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS product_variants (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    color varchar(50) NULL,
    size varchar(50) NULL,
    price_modifier numeric(12, 2) NOT NULL DEFAULT 0,
    stock integer NOT NULL DEFAULT 0,
    sku varchar(50) NULL UNIQUE,
    product_id bigint NOT NULL REFERENCES products(id) DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE products ADD COLUMN IF NOT EXISTS brand_id bigint NULL
    REFERENCES brands(id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS inventory_transactions (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transaction_type varchar(20) NOT NULL,
    quantity_changed integer NOT NULL,
    stock_after integer NOT NULL,
    reference_id varchar(100) NULL,
    notes text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT NOW(),
    product_id bigint NULL REFERENCES products(id) DEFERRABLE INITIALLY DEFERRED,
    variant_id bigint NULL REFERENCES product_variants(id) DEFERRABLE INITIALLY DEFERRED
);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_image_url"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Brand",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("description", models.TextField(blank=True)),
                    ],
                    options={
                        "db_table": "brands",
                    },
                ),
                migrations.CreateModel(
                    name="ProductVariant",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("color", models.CharField(blank=True, max_length=50, null=True)),
                        ("size", models.CharField(blank=True, max_length=50, null=True)),
                        (
                            "price_modifier",
                            models.DecimalField(decimal_places=2, default=0, max_digits=12),
                        ),
                        ("stock", models.IntegerField(default=0)),
                        (
                            "sku",
                            models.CharField(blank=True, max_length=50, null=True, unique=True),
                        ),
                        (
                            "product",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="variants",
                                to="product.product",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "product_variants",
                    },
                ),
                migrations.AddField(
                    model_name="product",
                    name="brand",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="product.brand",
                    ),
                ),
                migrations.CreateModel(
                    name="InventoryTransaction",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "transaction_type",
                            models.CharField(
                                choices=[
                                    ("IMPORT", "Nhập kho"),
                                    ("EXPORT", "Xuất kho"),
                                    ("ORDER", "Đơn hàng"),
                                    ("RETURN", "Hoàn trả"),
                                    ("ADJUST", "Điều chỉnh"),
                                ],
                                max_length=20,
                            ),
                        ),
                        ("quantity_changed", models.IntegerField()),
                        ("stock_after", models.IntegerField()),
                        (
                            "reference_id",
                            models.CharField(
                                blank=True,
                                help_text="Order ID, PO ID, etc.",
                                max_length=100,
                                null=True,
                            ),
                        ),
                        ("notes", models.TextField(blank=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "product",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="product.product",
                            ),
                        ),
                        (
                            "variant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="product.productvariant",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "inventory_transactions",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(CREATE_MISSING_TABLES, migrations.RunSQL.noop),
            ],
        ),
    ]
