# Generated by Django 4.2.29 on 2026-06-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX idx_product_search ON catalog_product USING gin(to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(description,'')));",
            reverse_sql="DROP INDEX IF EXISTS idx_product_search;"
        )
    ]

    def apply(self, project_state, schema_editor, collect_sql=False):
        if schema_editor.connection.vendor == 'postgresql':
            return super().apply(project_state, schema_editor, collect_sql)
        return project_state

