# Generated by Django 4.2.29 on 2026-05-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shippings',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_weight', models.FloatField(default=0)),
                ('max_weight', models.FloatField(default=0)),
                ('min_distance', models.FloatField(default=0)),
                ('max_distance', models.FloatField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'shipping_methods',
            },
        ),
        migrations.CreateModel(
            name='ShippingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='shipping.shipping')),
            ],
            options={
                'db_table': 'shipping_statuses',
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='ShippingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shipping.shippingmethod')),
            ],
            options={
                'db_table': 'shipping_features',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('address_line', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('shipping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='shipping.shipping')),
            ],
            options={
                'db_table': 'shipping_addresses',
            },
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingmethod'),
        ),
    ]
